const PRIMARY_RED_COLOR = "#E84C51";
const PRIMARY_YELLOW_COLOR = "#fbb403";
const PRIMARY_WHITE_COLOR = "#fff";

export { PRIMARY_YELLOW_COLOR, PRIMARY_WHITE_COLOR };
export default PRIMARY_RED_COLOR;
